### ISSUE TITLE
React issue

### ISSUE THREAD

**Issue by Redageddon** [ani-memes/amii-rider-extension#10]
It is reacting to literally nothing, when everything is turned on.

**Comment by Unthrottled** [comment]
That's curious, it's still working for me. I wonder if AMII is installed?

Could you go to `Help > About`  and copy the info and put it here?

Here is mine for example

```JetBrains Rider 2020.3.3
Build #RD-203.7148.30, built on February 20, 2021
Licensed to Alex Simons
You have a perpetual fallback license for this version.
Subscription is active until February 20, 2022.
Runtime version: 11.0.9.1+11-b1145.63 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
.NET Core 3.1.8
Linux 5.4.0-72-generic
GC: G1 Young Generation, G1 Old Generation
Memory: 512M
Cores: 12
Registry: debugger.new.debug.tool.window.view=true, ide.tree.horizontal.default.autoscrolling=false, performance.watcher.sampling.interval.ms=200, ide.borderless.tab.caption.in.title=false, ide.tooltip.showAllSeverities=true, show.diff.preview.as.editor.tab=true, ide.mac.bigsur.alerts.enabled=false, debugger.show.values.use.inlays=false, light.edit.file.open.enabled=false, performance.watcher.unresponsive.interval.ms=1000, search.everywhere.settings=true, show.diff.preview.as.editor.tab.with.single.click=true, parameter.info.max.visible.rows=10, ide.win.file.chooser.native=true, vcs.log.show.diff.preview.as.editor.tab=true, actionSystem.fix.alt.gr=false, search.everywhere.pattern.checking=false, ide.tooltip.initialDelay=0, ide.mac.bigsur.window.with.tabs.enabled=false, ide.require.transaction.for.model.changes=false, ide.debug.in.title=true, ide.new.project.model=false, rdclient.asyncActions=false
Non-Bundled Plugins: io.unthrottled.amii, io.unthrottled.amii.rider
Current Desktop: Unity
```

Also could you look through the logs and find anything interesting (or post it here)? 

`Help -> Diagnostic Tools -> Show log in files` (or explorer if you are on windows)

**Comment by Redageddon** [comment]
JetBrains Rider 2021.1.2
Build #RD-211.7142.19, built on April 22, 2021
Licensed to Redageddon
[REDACTED]
[REDACTED]
Runtime version: 11.0.10+9-b1341.41 amd64
VM: Dynamic Code Evolution 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
.NET Framework 4.0.30319.42000
GC: G1 Young Generation, G1 Old Generation
Memory: 6144M
Cores: 8
Registry: debugger.new.debug.tool.window.view=true, ide.tree.horizontal.default.autoscrolling=false, performance.watcher.sampling.interval.ms=200, ide.borderless.tab.caption.in.title=false, ide.tooltip.showAllSeverities=true, show.diff.preview.as.editor.tab=true, debugger.show.values.use.inlays=false, light.edit.file.open.enabled=false, performance.watcher.unresponsive.interval.ms=1000, search.everywhere.settings=true, show.diff.preview.as.editor.tab.with.single.click=true, parameter.info.max.visible.rows=10, ide.win.file.chooser.native=true, vcs.log.show.diff.preview.as.editor.tab=true, search.everywhere.pattern.checking=false, ide.tooltip.initialDelay=0, ide.require.transaction.for.model.changes=false, ide.debug.in.title=true, rdclient.asyncActions=false
Non-Bundled Plugins: io.unthrottled.amii (0.9.2), io.unthrottled.amii.rider (0.2.1), com.genuitec.codetogether (4.0.1-00895)

**Comment by Redageddon** [comment]
It started partially working, when i open rider, when a build fails and when i go afk for along time is the only time they show up

**Comment by Unthrottled** [comment]
Aight, I can reproduce the issue on `2021.1.2`, they must have changed something.

**Comment by Unthrottled** [comment]
Okay, so it's reacting to tests for me again after I restarted the IDE, which is a bit annoying.

**Comment by Unthrottled** [comment]
![Peek 2021-05-03 05-33](https://user-images.githubusercontent.com/15972415/116866567-3de71100-abd1-11eb-925d-e0519b570195.gif)

@Redageddon Just to make sure we are doing the same thing. :point_up: this is what I am doing.
Is that similar to what you are trying to do? (I showed it not working for me the first time)

**Comment by Redageddon** [comment]
Mine acts exactly the same as yours. (sorry for the late response was asleep then had school)

**Comment by Unthrottled** [comment]
Aight, I've submitted the plugin to be published to the marketplace. You can wait until then to take the new update, or you can follow [the manual installation](https://github.com/ani-memes/amii-rider-extension#installation) instructions to get the latest release with the fix. Thanks for bring this to my attention.
